source: public
timezone: Africa/Nairobi
verbose: false
  #layouts_dir: templates/
title: "Felix Muthui personal website"
url: "https://igwanya.github.io/felix-muthui/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
