source: public
timezone: Africa/Nairobi
verbose: false
  #layouts_dir: templates/
title: "Jekyll Actions Demo"
url: "https://igwanya.github.io/jekyll_webpage/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# files Jekyll should not delete from .site
keep_files:
  - css/tailwind.css
  - css/tailwind.css.map
