source: public
timezone: Africa/Nairobi
verbose: false
  #layouts_dir: templates/
title: "Jekyll Actions Demo"
url: "https://igwanya.github.io/felix-muthui/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# files Jekyll should not delete from .site
keep_files:
  - css/tailwind.css
  - css/tailwind.css.map
